version: '3'

services:
  python:
    image: python-with-dep
    build:
      context: .
      dockerfile: Dockerfile
    ports:
     - '8501:8501'
    working_dir: /app
    volumes:
      - "./app/:/app"
    env_file:
    - prod.env
    command: streamlit run dashboard.py
    depends_on:
      - mysql

  mysql:
    image: mysql/mysql-server:latest
    ports:
     - '3306:3306'
    env_file:
    - prod.env
    volumes:
      - "mysqldb-volume:/var/lib/mysql"
      - "./db/:/db"
    command: --init-file /db/init.sql


volumes:
  mysqldb-volume:
